#lang r5rs

(#%require "test-instruction.rkt")
(#%require "test-parser.rkt")
(#%require "test-element.rkt")
(#%require "test-sensor.rkt")
(#%require "test-actuator.rkt")
(#%require "test-device.rkt")
(#%require "test-steward.rkt")
(#%require "test-hardware-device.rkt")
(#%require "test-physical-room.rkt")
(#%require "test-xbee-simulation.rkt")
(#%require "test-zigbee.rkt")

(test-instruction)
(test-parser)
(test-element)
(test-sensor)
(test-actuator)
(test-device)
(test-steward)
(test-hardware-device)
(test-physical-room)
(test-xbee-simulation)
(test-zigbee)

(display "Finished testing !")